#!/bin/sh

gcloud deployment-manager deployments create gke-with-nat --config gke-with-nat-route.yml
gcloud container clusters get-credentials nat-gke-cluster --zone us-central1-b

kubectl apply -f kubernetes/nginx-pod.yml
echo "waiting for 10 seconds for  pod to start"
sleep 10
POD=$(kubectl get pods | grep frontend | awk '{print $1}')

echo "installing curl on container"
kubectl exec -it $POD -- apt-get update
kubectl exec -it $POD -- apt-get install -y curl

echo "Making request to postman-echo to test connectivity through container."
echo "postman-echo.com/ip returns the IP of the source request:"
kubectl exec -it $POD curl https://postman-echo.com/ip
echo
echo
echo "It should be the same than nat-vm external IP:"
gcloud compute instances list --format='value(EXTERNAL_IP)' --filter='NAME=nat-vm'
echo
echo "...and different than pod's node external IP:"
NODE_NAME=$(kubectl get pod $POD -o jsonpath='{ $.spec.nodeName }')
gcloud compute instances list --format='value(EXTERNAL_IP)' --filter="NAME=$NODE_NAME"
